$SubModuleUpdateBranch = "nightly-submodule-update"
$PackageUpdateBranch = "nightly-package-update"
$PropertiesUpdateBranch = "property-update"
$CopyrightUpdateBranch = "copyright-update"
$BaseGitUrl = "https://github.com/51degrees/"
