name: Generate Documentation Preview

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      org-name:
        required: false
        type: string
        default: 51degrees
      user:
        required: false
        type: string
        default: Automation51D
      email:
        required: false
        type: string
        default: "51DCI@51Degrees.com"
      dryrun:
        required: false
        type: string
        default: false
      separate-examples:
        required: false
        type: string
        default: false
      pull-request-id:
        required: false
        type: number
        default: 0
    secrets:
      token:
        required: true        

jobs:
  generate-documentation-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Checkout reusable workflow dir
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.org-name }}/common-ci
          path: common
            
      - name: Generate Documentation
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          $SeparateExamples = [bool]::Parse( "${{ inputs.separate-examples}}" )
          . ${{ github.workspace }}/common/generate-documentation.ps1 `
          -GitHubToken ${{ secrets.token }} `
          -RepoName ${{ inputs.repo-name }} `
          -OrgName ${{ inputs.org-name }} `
          -GitHubUser ${{ inputs.user }} `
          -GitHubEmail ${{ inputs.email }} `
          -PullRequestId ${{ inputs.pull-request-id }} `
          -SeparateExamples $SeparateExamples

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs_${{ inputs.pull-request-id }}
          path: ${{ github.workspace }}/common/${{ inputs.repo-name }}/*
          if-no-files-found: ignore
          include-hidden-files: true

      - name: Comment on PR
        shell: pwsh
        working-directory: ${{ github.workspace }}/common/
        run: |
          . ${{ github.workspace }}/common/steps/comment-on-issue.ps1 `
          -RepoName ${{ inputs.repo-name }} `
          -OrgName ${{ inputs.org-name }} `
          -GitHubToken ${{ secrets.token }} `
          -Id ${{ inputs.pull-request-id }} `
          -Message "Preview available [here](https://github.com/${{ inputs.org-name }}/${{ inputs.repo-name }}/actions/runs/${{ github.run_id }}#artifacts)."
          
